### PR TITLE
update pyproject.toml for python 3.13

### LINKED ISSUE #130: Update requires-python in pyproject.toml
Please refer to https://github.com/diffpy/diffpy.srmise/pull/143 for the changes in pyproject.toml

### PR DESCRIPTION
**Pull request by alisnwu**
closes #130

### CODE REVIEW

**Comment by alisnwu** [comment]
@sbillinge ready for review

**Comment by bobleesj** [comment]
@alisnwu we might need to wait for this PR to be merged since we have v3.4.3 awaiting to be released first. 

 you could close this PR for now and re-open after https://github.com/diffpy/diffpy.utils/issues/134 is closed

**Comment by bobleesj** [comment]
Lets re open after testing the full release version

**Comment by sbillinge** [comment]
3.4.3 merged so I am reopening this and I can merge it, it looks fine.  But there are some more issues to merge before we push this out.

**Pull request merged**
