### PR TITLE
Finalize diffpy.utils documentation

### PR DESCRIPTION
**Pull request by Sparks29032**
Fix Jupyter incompatibility -> added additional json enconding.
[new docs.zip](https://github.com/diffpy/diffpy.utils/files/13210543/html.zip)

### CODE REVIEW

**Review by sbillinge — COMMENTED** [review]
looks good to me.   Let me know if/when it is ready to merge.   I think it needs a news for the rever release.

**Comment by Sparks29032** [comment]
I think good to merge! I had a news in a previous PR with the same branch name, but I can add it after my class ends at 2:30pm.

**Comment by Sparks29032** [comment]
Running ``rever 3.2.4`` should add the final news file (other were added using ``rever -a changelog <version>``) and it should automatically cause the new documentation to build and deploy. Added a note about changelog to group wiki too (since changelog action didn't work unless ``CHANGELOG.rst`` had a particular header).

**Comment by Sparks29032** [comment]
[html.zip](https://github.com/diffpy/diffpy.utils/files/13302465/html.zip)
Current state of docs

**Comment by sbillinge** [comment]
super, I merged.  I do'nt have time to run rever atm, but will do it when I am back from Switzerland on Monday.  Please remind me to do it (I WILL forget....)

**Pull request merged**
